<?php

namespace Database\Seeders\Compras;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProveedorSeeder extends Seeder
{
    public function run(): void
    {
        $proveedores = [
            [
                'razon_social' => 'DISTRIBUIDORA PLOMERÍA DEL ESTE S.A.',
                'nombre_fantasia' => 'Plomería del Este',
                'ruc' => '80045678-9',
                'dv' => '9',
                'tipo_persona' => 'JURIDICA',
                'tipo_proveedor' => 'PRODUCTOS',
                'telefono' => '021-445566',
                'celular' => '0981-445566',
                'email' => 'ventas@plomeriadeleste.com.py',
                'sitio_web' => 'www.plomeriadeleste.com.py',
                'direccion' => 'Av. Eusebio Ayala Km 5.5',
                'ciudad' => 'Asunción',
                'departamento' => 'Central',
                'pais' => 'Paraguay',
                'contacto_nombre' => 'María González',
                'contacto_cargo' => 'Gerente Comercial',
                'contacto_telefono' => '0981-445566',
                'contacto_email' => 'mgonzalez@plomeriadeleste.com.py',
                'dias_plazo_pago' => 30,
                'limite_credito' => 50000000,
                'descuento_habitual' => 5,
                'banco' => 'Banco Continental',
                'tipo_cuenta' => 'Corriente',
                'numero_cuenta' => '1234567890',
                'activo' => true,
                'es_nacional' => true,
                'contribuyente' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'razon_social' => 'IMPORTADORA TUBERÍAS Y ACCESORIOS S.R.L.',
                'nombre_fantasia' => 'ITA Importaciones',
                'ruc' => '80056789-1',
                'dv' => '1',
                'tipo_persona' => 'JURIDICA',
                'tipo_proveedor' => 'PRODUCTOS',
                'telefono' => '021-556677',
                'celular' => '0982-556677',
                'email' => 'compras@ita.com.py',
                'sitio_web' => 'www.ita.com.py',
                'direccion' => 'Ruta Transchaco Km 12',
                'ciudad' => 'Mariano Roque Alonso',
                'departamento' => 'Central',
                'pais' => 'Paraguay',
                'contacto_nombre' => 'Carlos Martínez',
                'contacto_cargo' => 'Jefe de Ventas',
                'contacto_telefono' => '0982-556677',
                'contacto_email' => 'cmartinez@ita.com.py',
                'dias_plazo_pago' => 60,
                'limite_credito' => 80000000,
                'descuento_habitual' => 8,
                'banco' => 'Banco Itaú',
                'tipo_cuenta' => 'Corriente',
                'numero_cuenta' => '9876543210',
                'activo' => true,
                'es_nacional' => true,
                'contribuyente' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'razon_social' => 'FERRETERÍA CENTRAL Paraguay S.A.',
                'nombre_fantasia' => 'Ferretería Central',
                'ruc' => '80067890-2',
                'dv' => '2',
                'tipo_persona' => 'JURIDICA',
                'tipo_proveedor' => 'PRODUCTOS',
                'telefono' => '021-667788',
                'celular' => '0983-667788',
                'email' => 'ventas@ferreteriacentral.com.py',
                'sitio_web' => 'www.ferreteriacentral.com.py',
                'direccion' => 'Av. Artigas 2345',
                'ciudad' => 'Asunción',
                'departamento' => 'Central',
                'pais' => 'Paraguay',
                'contacto_nombre' => 'Ana Rodríguez',
                'contacto_cargo' => 'Gerente de Ventas',
                'contacto_telefono' => '0983-667788',
                'contacto_email' => 'arodriguez@ferreteriacentral.com.py',
                'dias_plazo_pago' => 15,
                'limite_credito' => 30000000,
                'descuento_habitual' => 3,
                'banco' => 'Banco Regional',
                'tipo_cuenta' => 'Corriente',
                'numero_cuenta' => '1122334455',
                'activo' => true,
                'es_nacional' => true,
                'contribuyente' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'razon_social' => 'DISTRIBUIDORA TIGRE PARAGUAY S.A.',
                'nombre_fantasia' => 'Tigre Paraguay',
                'ruc' => '80078901-3',
                'dv' => '3',
                'tipo_persona' => 'JURIDICA',
                'tipo_proveedor' => 'PRODUCTOS',
                'telefono' => '021-778899',
                'celular' => '0984-778899',
                'email' => 'pedidos@tigrepy.com.py',
                'sitio_web' => 'www.tigre.com.py',
                'direccion' => 'Av. Madame Lynch 3450',
                'ciudad' => 'Asunción',
                'departamento' => 'Central',
                'pais' => 'Paraguay',
                'contacto_nombre' => 'Roberto Silva',
                'contacto_cargo' => 'Ejecutivo de Ventas',
                'contacto_telefono' => '0984-778899',
                'contacto_email' => 'rsilva@tigrepy.com.py',
                'dias_plazo_pago' => 45,
                'limite_credito' => 100000000,
                'descuento_habitual' => 10,
                'banco' => 'Banco Familiar',
                'tipo_cuenta' => 'Corriente',
                'numero_cuenta' => '5544332211',
                'activo' => true,
                'es_nacional' => true,
                'contribuyente' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'razon_social' => 'COMERCIAL HIDRÁULICA SUR S.R.L.',
                'nombre_fantasia' => 'Hidráulica Sur',
                'ruc' => '80089012-4',
                'dv' => '4',
                'tipo_persona' => 'JURIDICA',
                'tipo_proveedor' => 'PRODUCTOS',
                'telefono' => '021-889900',
                'celular' => '0985-889900',
                'email' => 'contacto@hidraulicasur.com.py',
                'sitio_web' => 'www.hidraulicasur.com.py',
                'direccion' => 'Ruta 1 Km 25',
                'ciudad' => 'San Lorenzo',
                'departamento' => 'Central',
                'pais' => 'Paraguay',
                'contacto_nombre' => 'Laura Benítez',
                'contacto_cargo' => 'Gerente General',
                'contacto_telefono' => '0985-889900',
                'contacto_email' => 'lbenitez@hidraulicasur.com.py',
                'dias_plazo_pago' => 30,
                'limite_credito' => 40000000,
                'descuento_habitual' => 7,
                'banco' => 'Banco GNB',
                'tipo_cuenta' => 'Corriente',
                'numero_cuenta' => '6677889900',
                'activo' => true,
                'es_nacional' => true,
                'contribuyente' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('compras.proveedores')->insert($proveedores);

        $this->command->info('✓ 5 proveedores creados exitosamente');
    }
}
